apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
      - name: zipkin-server
        image: iancollington/zipkin-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.25"
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  labels:
    app: zipkin-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31004
    protocol: TCP
  selector:
    app: zipkin-server
