apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hystrix-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hystrix-dashboard
    spec:
      containers:
      - name: hystrix-dashboard
        image: iancollington/hystrix-dashboard
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.25"
            memory: 1024Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hystrix-dashboard
  labels:
    app: hystrix-dashboard
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hystrix-dashboard
